
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package grammar;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int FORM = 18;
  public static final int OPERATION = 3;
  public static final int POS = 20;
  public static final int GOV = 42;
  public static final int RANDOM = 23;
  public static final int DEPENDENCY = 21;
  public static final int SLASH = 35;
  public static final int EQUALS = 29;
  public static final int MINUS = 46;
  public static final int TILDE = 49;
  public static final int DELETE = 9;
  public static final int STAR = 32;
  public static final int SEMICOLON = 37;
  public static final int COPY = 13;
  public static final int FIRST = 24;
  public static final int QUOTATION = 28;
  public static final int FEATS = 16;
  public static final int ZERO = 44;
  public static final int COMMA = 30;
  public static final int BEGIN = 4;
  public static final int PIPELINE = 2;
  public static final int PLUS = 31;
  public static final int EXCLAMATION = 47;
  public static final int IF = 7;
  public static final int AMPERSAND = 48;
  public static final int LEFT = 39;
  public static final int EOF = 0;
  public static final int LINEBREAK = 38;
  public static final int SEARCH = 6;
  public static final int error = 1;
  public static final int PIPE = 36;
  public static final int NUMBER = 43;
  public static final int BRACKETS_RIGHT = 34;
  public static final int DEBUG = 25;
  public static final int SPLIT = 11;
  public static final int BRACKETS_LEFT = 33;
  public static final int FROM = 10;
  public static final int MOVE = 12;
  public static final int COLON = 27;
  public static final int ELSE = 8;
  public static final int SAVE = 26;
  public static final int DEP = 41;
  public static final int INSERT = 14;
  public static final int LEMMA = 19;
  public static final int END = 5;
  public static final int QUESTION = 51;
  public static final int STRING = 45;
  public static final int ALL = 17;
  public static final int SEQUENCE = 22;
  public static final int RIGHT = 40;
  public static final int SEMGREX = 50;
  public static final int REPLACE = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PIPELINE",
  "OPERATION",
  "BEGIN",
  "END",
  "SEARCH",
  "IF",
  "ELSE",
  "DELETE",
  "FROM",
  "SPLIT",
  "MOVE",
  "COPY",
  "INSERT",
  "REPLACE",
  "FEATS",
  "ALL",
  "FORM",
  "LEMMA",
  "POS",
  "DEPENDENCY",
  "SEQUENCE",
  "RANDOM",
  "FIRST",
  "DEBUG",
  "SAVE",
  "COLON",
  "QUOTATION",
  "EQUALS",
  "COMMA",
  "PLUS",
  "STAR",
  "BRACKETS_LEFT",
  "BRACKETS_RIGHT",
  "SLASH",
  "PIPE",
  "SEMICOLON",
  "LINEBREAK",
  "LEFT",
  "RIGHT",
  "DEP",
  "GOV",
  "NUMBER",
  "ZERO",
  "STRING",
  "MINUS",
  "EXCLAMATION",
  "AMPERSAND",
  "TILDE",
  "SEMGREX",
  "QUESTION"
  };
}

